### ISSUE TITLE
Sound doesn't come out

### ISSUE THREAD

**Issue by looklukelike** [shannonsans/PianoSpots#1]
Hey,
Glad to have found this repo. I had to edit the size() line of code in void setup() to run it decently on Safari. The interaction works ok (creating circles whenever the user clicks on screen), but the sound is not coming out. Are you sure that you linked the .wav files properly?
Running on OSX and Processing IDE latest version.

**Comment by shannonsans** [comment]
The sound works in Chrome but Safari is throwing a JavaScript error related to the Web Audio API in the maxim.js file, which I forked from https://github.com/micknoise/Maxim but hasn't been updated in quite some time. I made a couple of changes this last year so it would work with both webkitAudioContext and AudioContext so that Chrome would work, and I probably broke something in Safari. I probably won't have a chance to look at it soon, but you can see my changes to the file in https://github.com/shannonsans/PianoSpots/commits/master/maxim.js and see if reverting them makes a difference.

**Comment by shannonsans** [comment]
OK, for some reason Safari does not like the line

`context = new AudioContext() || new webkitAudioContext()

and instead throws an exception.

This is how every website I've seen indicates to do the check, and I know it was working before, because I was showing it to people on my phone using Safari.

At any rate, moving things into a try/catch block seems to have fixed the Safari problem.

**Comment by shannonsans** [comment]
Found the culprit:
Safari was throwing an exception for this:
`var context = new AudioContext() || webkitAudioContext()`

However it will accept this:
`var context = new (window.AudioContext || window.webkitAudioContext)();`

Should be working now.
